config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'foods#index'
 
  resources :users, only: [:edit]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :inventories, only: [:index, :show, :new, :create, :destroy, :update] do 
    resources :inventory_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :shopping_lists, only: [:index]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/about', to: 'recipes#about'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  has_many :inventory_foods

  validates :name, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[show edit update destroy]

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
    @inventory_foods = InventoryFood.includes(:food).where(inventory_id: @inventory.id)
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = current_user.inventories.build(inventory_params)
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, html: {class: "inventory-form"}) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'name-field' %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit class: 'add-inventory' %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
 <li id="<%= dom_id inventory %>">
    <strong>Name:</strong>
    <%= link_to inventory.name, inventory_url(inventory) %>
     <%= button_to "Remove", inventory, method: :delete %>
     </li>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="inventory-container">

<ul class="inventories-container" id="inventories">
  <% @inventories.each_with_index do |inventory, index| %>
  <% if can? :manage, inventory %>
     <li id="<%= dom_id inventory %>">
      <div class="inventory-element">
        <h2><%= link_to inventory.name, inventory_url(inventory), class: 'inven-names' %></h2>
        <p><%= button_to "Remove", inventory, method: :delete, class: "recipe-remove" %></p>
      </div>
      <p>
        <%= inventory.description%>
      </p>
     </li>
     <% end %>
  <% end %>
</ul>

<%= link_to "Add Inventory", new_inventory_path, class: 'add-inventory' %>
</section>

app/views/inventories/new.html.erb
<section class="inventory-container">
<h1 class="inventory-title">New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path, class: 'add-inventory' %>
</div>
</section>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>
 <section class="inventory-container">
  <% if can? :manage, @inventory %>
    <h1 class="inventory-title"> Inventory <%= @inventory.id %> </h1>
    <div class="add-new-food">
    <%= link_to "Add food", new_inventory_inventory_food_path(@inventory.id), class: 'add-inventory' %>
     <% end %>
     </div>
     <hr style="width:500px;">
   <table class="inventory-food-tale">
  <thead>
    <tr class="head-table">
      <th>Food</th>
      <th>Quantity</th>
      <th>Actions</th>
      </tr>
  </thead>

  <tbody>
    <% @inventory_foods.each do |inventory_food| %>
      <tr class="inventory-tr">
        <td><%= inventory_food.food.name %></td>
        <td><%= inventory_food.quantity %></td>
        <td><%= button_to "Remove", inventory_inventory_food_path(inventory_food.inventory.id, inventory_food.id), method: :delete, class: 'add-inventory', class: 'btn-submit' %></td>

      </tr>
    <%end %>
  </tbody>
</table>

  <div>
  <%= link_to "Back to inventories", inventories_path, class: 'add-inventory' %>
</div>
 </section>