config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'foods#index'
 
  resources :users, only: [:edit]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :inventories, only: [:index, :show, :new, :create, :destroy, :update] do 
    resources :inventory_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :shopping_lists, only: [:index]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/about', to: 'recipes#about'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  has_many :recipe_foods

  validates :name, presence: true
  validates :description, presence: true

  def total_food_items
    recipe_foods.count
  end

  def total_price
    total = 0
    recipe_foods.each do |recipe_food|
      total += recipe_food.quantity * recipe_food.food.price
    end
    total
  end

  def own?
    user_id == current_user.id
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.recipe_foods.destroy_all

    respond_to do |format|
      if @recipe.destroy
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :delete, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def about; end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="recipe-container">
  <p>
    Recipe <%= recipe.id %> : <strong><%= recipe.name %></strong>
  </p>

  <div class="recipe-body">
    <div class="recipe-left">
      <p>
        <strong>Preparation time:</strong>
        <%= recipe.preparation_time %>
      </p>

      <p>
        <strong>Cooking time:</strong>
        <%= recipe.cooking_time %>
      </p>
    </div>

    <div class="recipe-public">
      <p>          
        <% if recipe.public %>
          <p>Public</p>
        <% else %>
          <p>Private</p>
        <% end %>
      </p>

      <p>
        <% if current_user.id === recipe.user_id %>
          <%disabled = false%>
        <%else%>
          <%disabled = true%>
        <%end%>
          
        <%= form_with(model: recipe) do |form| %>
          <label class="switch">
          <%= form.check_box :public, 
            :disabled => disabled,
            :class => "status-checkbox",
            :role => "switch",
            :onclick => "this.form.submit()" %>
          <span class="slider round"></span>
        <% end %>
      </p>
    </div>
  </div>

  <div class="recipe-text">
    <strong>Steps go here:</strong><br>
    <%= recipe.description %>
  </div>
</div>

app/views/recipes/about.html.erb
<div>
<br>
<h1>Recipe App</h1>
<p>
The Recipe app keeps track of all your recipes,ingredients, and inventory. <br>
It allows you to save ingredients, keep track of what you have, create recipes, <br>
and generate a shopping list based on what you have and what you are missing <br>
from a recipe. Also, since sharing recipes is an important part of cooking the <br>
app allows you to make them public so anyone can access them.<br>
<br>
<strong>Please follow the links in navigation menu on the top of the page.</strong>
<p>****************************************************************************************</p>
</p>
<h1>Authors:</h1><br>
<br>
<strong>👤 **Andy**</strong><br>

- GitHub: <a href=https://github.com/TechnoAndy>[TechnoAndy]</a><br>
- Twitter: <a href=https://twitter.com/ADiegaardt>[@ADiegaardt]</a><br>
- LinkedIn: <a href=https://www.linkedin.com/in/andy-diegaardt/>[andy-diegaardt]</a><br>
<br>
<strong>👤 **Peter**</strong><br>
<br>
- GitHub: <a href=https://github.com/anyepeter>[anyepeter]</a><br>
- Twitter: <a href=https://twitter.com/apcode>[@apcode]</a><br>
- LinkedIn: <a href=https://www.linkedin.com/in/peter-chendi/>[peter-chendi]</a><br>
<br>
<strong>👤 **Serg**</strong><br>
<br>
- GitHub: <a href=https://github.com/SergSkol>[SergSkol]</a><br>
- Twitter: <a href=https://twitter.com/sps676>[@sps676]</a><br>
- LinkedIn: <a href=https://www.linkedin.com/in/sergskol/>[SergSkol]</a><br>
<br>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="recipes" class="recipe-container">
  <% @recipes.each do |recipe| %>
    <% if (current_user.id == recipe.user_id) || (current_user.admin?) %> 
      <div class="recipe-element">
        <div class="recipe-head">
          <h2><%= link_to "Recipe #{recipe.id}", recipe_path(recipe.id) %></h2>
          <p>
            <% if can? :destroy, recipe %>
              <%= button_to "REMOVE", recipe, method: :delete, class: "recipe-remove" %>
            <% end %>
          </p>
        </div>
        <div class="recipe-descr">
          <p><%= recipe.name%>: <%= recipe.description %></p>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<div class="recipe-footer">
  <%= link_to "New recipe", new_recipe_path, class: 'btn-submit' %>
</div>

app/views/recipes/new.html.erb
<div class="recipe-container">
  <h1>New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <br>

  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="recipe-title">Public Recipes</h1>
  <div class="recipe-container">
    <% @recipes.each do |recipe| %>
    <div class="recipe-element">
      <div class="recipe-head">
        <p><strong><%= link_to "#{recipe.name}", recipe_path(recipe.id) %></strong></p>
        <p>By: <%= User.find(recipe.user_id).name %></p>
      </div>
      <div class="recipe-descr">
        <p><span> Total food items: </span><%= recipe.total_food_items %></p>
        <p><span> Total price: $</span><%= recipe.total_price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<h1>General Shopping list</h1>
<div>
  Under constraction...
</div>

app/views/recipes/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "modal.js" %>
<% end %>

<p style="color: green"><%= notice %></p>

<div class="recipe-container">
  <%= render @recipe %>

  <div class="recipe-actions">
    <% if @inventories.empty? %>
      <h3>No inventory exists</h3>
    <%else%>
      <button type="button", class="btn-submit"
        id="btn-choose-inventory"
        onclick="showModal()"
        data-toggle="modal"
        data-target="#modalChooseInventory">
          Generate shopping list
      </button>
    <% end %>

    <% if can? :manage, @recipe %>
      <%= button_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), method: :get, class: 'btn-submit' %>
    <%end%>
  </div>

  <div class=recipe-line></div>

  <table class="recipe-food-table">
    <thead class="recipe-head-table">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th><td><%= recipe_food.food.name %></td>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr class="recipe-tr">
          
          <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
          <td>$<%= recipe_food.quantity * recipe_food.food.price%></td>
          <td>
          <div class="recipe-table-actions">
            <% if can? :manage, @recipe %>
              <%= button_to "Modify", edit_recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :get, class: "recipe-remove" %>
              <%= button_to "Remove", recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :delete, class: "recipe-remove"%>
            <%end%>
            <div>
          </td>
        </tr>
      <%end %>
    </tbody>
  </table>

  <div class="recipe-footer">
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: 'add-inventory' %> |
    <%= link_to "Back to recipes", recipes_path, class: 'add-inventory' %>

  </div>
</div>
</section>

<div class="recipe-modal hide" id="modalChooseInventory">
  <h5 id="modalChooseInventoryLabel">Generating Shopping List</h5>

  <div class="modal-body">
    <h6>Choose an inventory to use</h6>
    <%= form_with url: shopping_lists_path, class: "recipe-modal-selector", method: :get do |form| %>
      <%- @inventories = Inventory.includes(:user ).where(user_id: current_user.id) %>
      <%= form.select :inventory_id, @inventories.map { |i| [i.name, i.id] } %>
      <%= form.number_field :recipe_id, value: @recipe.id, hidden: true %>

      <div class="recipe-modal-footer">

        <%= form.submit "Generate", data: { turbo: false }, class: 'btn-submit' %>

      </div>
    <% end %>
  </div>
</div>