config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'foods#index'
 
  resources :users, only: [:edit]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :inventories, only: [:index, :show, :new, :create, :destroy, :update] do 
    resources :inventory_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :shopping_lists, only: [:index]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/about', to: 'recipes#about'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id', class_name: 'Food'
  belongs_to :recipe, foreign_key: 'recipe_id', class_name: 'Recipe'

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def show; end

  def new
    @foods = Food.includes(:user).where(user_id: current_user.id)
    @recipe_id = params[:recipe_id]
    @recipe = Recipe.find(params[:recipe_id])

    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find_by(id: params[:id])
  end

  def create
    @foods = Food.all
    @recipe_id = params[:recipe_id]
    @recipe = Recipe.find(params[:recipe_id])

    @recipe_food = RecipeFood.new(recipe_food_params)

    unless @recipe.recipe_foods.find_by(food_id: recipe_food_params[:food_id]).nil?
      redirect_to recipe_url(@recipe), alert: 'Such ingredient for this recipe already exists!'
      return
    end

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_id = params[:recipe_id]
    @recipe = Recipe.find(@recipe_id)

    respond_to do |format|
      if @recipe_food.update(edit_recipe_food_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end

  def edit_recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<div>
  <%= form_with(url: recipe_recipe_foods_path, scope: :recipe_food) do |form| %>
    <% if recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

        <ul>
          <% recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :recipe_id, value: @recipe_id %>
    <p>Ingredients for recipe # <%= @recipe_id %> </p>

    <div>
      <%= form.label :food_id %>
      <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
    </div>

    <div>
      <%= form.label :quantity %>
      <%= form.number_field :quantity %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<div class="recipe-container">
  <h1>Editing recipe food</h1>

  <%= form_with(model: @recipe_food, url: recipe_recipe_food_path, method: "patch") do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :quantity %>
      <%= form.text_field :quantity %>
    </div>

    <div>
      <%= form.submit "Update" %>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Back to recipe", recipe_path(@recipe) %>
  </div>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="recipe-container">
  <h1>New recipe food</h1>

  <%= render "form", recipe_food: @recipe_food %>

  <br>

  <div>
    <%= link_to "Back to recipe", recipe_path(@recipe) %>
  </div>
<div class="recipe-container">

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>