config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'foods#index'
 
  resources :users, only: [:edit]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :inventories, only: [:index, :show, :new, :create, :destroy, :update] do 
    resources :inventory_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :shopping_lists, only: [:index]

  get '/public_recipes', to: 'recipes#public_recipes'
  get '/about', to: 'recipes#about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "inventory", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= javascript_include_tag "application" %>
    <%= yield :javascript_includes %>
  </head>

  <body>

    <nav class="navbar">
      <div class="navbar-identifier">
      <span>
        <% if user_signed_in? %> Logged in as <strong> <%= current_user.name %></strong>
        </span>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"  %> 
      </div>
      <%= link_to "Foods", foods_path, class: "navbar-link" %> |
      <%= link_to "Recipes", recipes_path, class: "navbar-link" %> |
      <%= link_to "Public recipes", public_recipes_path, class: "navbar-link" %> |
      <%= link_to "Inventories", inventories_path, class: "navbar-link" %> |
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "About", about_path, class: "navbar-link" %>
      <% end %>
    </nav>

    <p class="alert" style="color: red"><%= alert %></p>
      <%= yield %>
  </body>
</html>